# Generated by Django 4.2.2 on 2023-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPlanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('rent', models.FloatField()),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('hotel_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
            ],
        ),
    ]
