# Generated by Django 4.2.2 on 2023-06-28 17:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourPlanner', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
