# Generated by Django 4.2.3 on 2023-08-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPlanner', '0003_alter_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('person', models.IntegerField()),
                ('destination', models.CharField(max_length=256)),
                ('hotelRoom', models.CharField(max_length=256)),
                ('transport', models.CharField(max_length=256)),
                ('datetime', models.CharField(max_length=128)),
                ('food', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('package_image1', models.ImageField(blank=True, null=True, upload_to='package_images/details')),
                ('package_image2', models.ImageField(blank=True, null=True, upload_to='package_images/details')),
                ('package_image3', models.ImageField(blank=True, null=True, upload_to='package_images/details')),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
    ]
